wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717193292
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.17.0
      6: 4.41.1
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
lr:
  desc: null
  value: 0.00025
gamma:
  desc: null
  value: 0.95
buffer_size:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 32
loss_fn:
  desc: null
  value: mse_loss
device:
  desc: null
  value: cpu
seed:
  desc: null
  value: 42
save_path:
  desc: null
  value: ./runs/DQN/run10
